### ISSUE TITLE
SQLite Insert error: models: unable to insert into file: near "RETURNING": syntax error

### ISSUE THREAD

**Issue by gennaios** [volatiletech/sqlboiler#1050]
### What version of SQLBoiler are you using (`sqlboiler --version`)?

4.8.3

### What is your database and version (eg. Postgresql 10)

SQLite3

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

```
CREATE TABLE IF NOT EXISTS "file" (
	"id"	INTEGER NOT NULL,
	"path"	text NOT NULL,
	"name"	text NOT NULL,
	"extension"	varchar(3) NOT NULL,
	"size"	integer NOT NULL,
	"title"	text,
	"publisher"	text,
	"publisher_id"	INTEGER,
	"creator"	text,
	"subject"	text,
	"language"	text,
	"description"	text,
	"date_created"	datetime NOT NULL,
	"date_modified"	datetime NOT NULL,
	"date_accessed"	datetime,
	"rating"	integer,
	"hash"	varchar(64) NOT NULL,
	PRIMARY KEY("id")
);
```

### Further information. What did you do, what did you expect?

Just getting started migrating to SQLBoiler. Module looks very nice and well maintained. I have just about everything working though I am not able to create a new record in one particular table. Inside a transaction, code is the following:

	```
var newFile models.File

	newFile.Path = book
	newFile.Name = filepath.Base(book)
	newFile.Extension = strings.ToLower(filepath.Ext(book)[1:]) // filepath.Ext returns with dot
	newFile.Size = stat.Size()
	newFile.Title = null.StringFrom(f.title)
	newFile.Publisher = null.StringFrom(f.publisher)
	newFile.Creator = null.StringFrom(f.creator)
	newFile.Subject = null.StringFrom(f.subject)
	newFile.DateCreated = dateCreated
	newFile.DateModified = dateModified
	newFile.DateAccessed = null.TimeFrom(t.AccessTime().UTC().Truncate(time.Millisecond))
	newFile.Hash = hash

        err = newFile.Insert(db.ctx, db.db, boil.Infer())
```

As a workaround, I am using a raw query. Any assistance would be appreciated.

**Comment by stephenafamo** [comment]
At first look at the code, my first thought is that `newFile` should be a pointer.... 

```go
var newFile = &models.File{}
```

Can you try that and see if it works?

**Comment by gennaios** [comment]
I’ll try to try such soon though I’m pretty sure I also did. Plus the above syntax I believe is similar to the listed example in the README. 

Looking at the SQLite forums, maybe the build is linking against some older sqlite without RETURNING support? 

A somewhat related question, I am not exactly sure how to build a specific module such as sqlite with various features, e.g. stat4. I specify the tags to build my module yet I am not sure if that causes such to be passed to each dependency. Maybe what I am doing is correct yet I think maybe it’s not working as I don’t see any stat4 table. 

I tried before looking but at the time didn’t find much. I’ll try to look for docs, maybe some provided by this project when using sqlite, if not already, could be of use.

**Comment by stephenafamo** [comment]
After creating a databse with your exact schema, it worked just fine for me using this code

```go
package main

import (
	"context"
	"database/sql"
	"path/filepath"
	models "playground/models/sqlite3"
	"strings"
	"time"

	_ "github.com/mattn/go-sqlite3"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
)

func main() {
	db, err := sql.Open("sqlite3", "test.db")
	if err != nil {
		panic(err)
	}

	book := "/a/b/c/book.pdf"

	var newFile = &models.File{}

	newFile.Path = book
	newFile.Name = filepath.Base(book)
	newFile.Extension = strings.ToLower(filepath.Ext(book)[1:])
	newFile.Size = 1020
	newFile.Title = null.StringFrom("A fancy book")
	newFile.Publisher = null.StringFrom("Boiling Press")
	newFile.Creator = null.StringFrom("Stephen")
	newFile.Subject = null.StringFrom("Issues")
	newFile.DateCreated = time.Now()
	newFile.DateModified = time.Now()
	newFile.DateAccessed = null.TimeFrom(time.Now())
	newFile.Hash = "weeee"

	err = newFile.Insert(context.Background(), db, boil.Infer())
	if err != nil {
		panic(err)
	}
}
```

My local sqlite version is `3.36.0`, but the `github.com/mattn/go-sqlite3` library uses `3.37.0`. Perhaps you can compare that with your own sqlite version to see.

Also, can you confirm that when generating the models, you reinstalled and then use [the sqlite3 driver](https://github.com/volatiletech/sqlboiler-sqlite3)?

**Comment by gennaios** [comment]
Thanks stephenafamo,

It's possible some of the used modules aren't correct. I'm not sure what is meant by ensuring use of that sqlite3 driver. My knowledge of Go could be better.

On macOS, I removed the package cache, ~/Go, and reinstalled all. From reporting of required imports, I don't see any use of sqlboiler-sqlite3, also not in the models. 

Same error. If you wish to look at the code, opening of database is here:

https://github.com/gennaios/alfred-jnana/blob/cb586624b0e66d4c632b36d4d089e0f104903a7b/internal/database/database.go#L16

and the tried insertion:

https://github.com/gennaios/alfred-jnana/blob/cb586624b0e66d4c632b36d4d089e0f104903a7b/internal/files/files.go#L181

**Comment by stephenafamo** [comment]
What commands did you use to generate the models?

When you do an insert using the model, what error do you get?

**Comment by gennaios** [comment]
sqlboiler sqlite3

Models are generated it seems correctly. Everything works though I am either using raw SQL to insert records or sometimes using models.[NAME]....One/All to fetch records. Error is as listed in issue title:

unable to insert into file: near "RETURNING": syntax error 

Looking through models, I see import of "github.com/mattn/go-sqlite3" and various sqlboiler entries but nothing related to the sqlboiler sqlite3 library, if that is the issue.

**Comment by stephenafamo** [comment]
@gennaios  What commands did you use to generate the models?

**Comment by gennaios** [comment]
`./sqliboiler sqlite3`

sqlboiler.toml:

```
[sqlite3]
dbname = "/Users/gary/Library/Application Support/Alfred/Workflow Data/io.github.gennaios.jnana/jnana.db"
blacklist = ["file_search", "bookmark_search", "sqlite_stat1"]
```

Generated model: https://github.com/gennaios/alfred-jnana/tree/master/models

Full schema:

`sqlite> .schema
CREATE TABLE sqlite_stat1(tbl,idx,stat);
CREATE TABLE IF NOT EXISTS 'file_search_data'(id INTEGER PRIMARY KEY, block BLOB);
CREATE TABLE IF NOT EXISTS 'file_search_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS 'file_search_docsize'(id INTEGER PRIMARY KEY, sz BLOB);
CREATE TABLE IF NOT EXISTS 'file_search_config'(k PRIMARY KEY, v) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS 'bookmark_search_data'(id INTEGER PRIMARY KEY, block BLOB);
CREATE TABLE IF NOT EXISTS 'bookmark_search_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS 'bookmark_search_docsize'(id INTEGER PRIMARY KEY, sz BLOB);
CREATE TABLE IF NOT EXISTS 'bookmark_search_config'(k PRIMARY KEY, v) WITHOUT ROWID;
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "creator" (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"name"	TEXT NOT NULL
);
CREATE INDEX "creator_on_name" ON "creator" (
	"name"
);
CREATE VIRTUAL TABLE file_search USING fts5(
		name,
		title,
		creator,
		subject,
		publisher,
		description,
		content='file',
		content_rowid='id',
		prefix='3',
		tokenize='porter unicode61 remove_diacritics 2'
	)
/* file_search(name,title,creator,subject,publisher,description) */;
CREATE VIRTUAL TABLE bookmark_search USING fts5(
		title,
		section,
		name,
		file_title,
		creator,
		subject,
		publisher,
		content='bookmark_view',
		content_rowid='id',
		prefix='3',
		tokenize='porter unicode61 remove_diacritics 2'
	)
/* bookmark_search(title,section,name,file_title,creator,subject,publisher) */;
CREATE TABLE IF NOT EXISTS "bookmark" (
	"id"	INTEGER NOT NULL,
	"file_id"	INTEGER NOT NULL,
	"title"	TEXT,
	"section"	TEXT,
	"destination"	TEXT NOT NULL,
	"date_accessed"	datetime,
	FOREIGN KEY("file_id") REFERENCES "file"("id") ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY("id")
);
CREATE INDEX "bookmark_file_id" ON "bookmark" (
	"file_id"
);
CREATE INDEX "bookmark_date_accessed" ON "bookmark" ( "date_accessed" );
CREATE TABLE IF NOT EXISTS "subject" ( "id"	INTEGER PRIMARY KEY AUTOINCREMENT, "name"	TEXT NOT NULL );
CREATE TABLE IF NOT EXISTS "publisher" ( "id"	INTEGER PRIMARY KEY AUTOINCREMENT, "name"	TEXT NOT NULL );
CREATE INDEX "publisher_on_name" ON "publisher" ( "name" );
CREATE TABLE IF NOT EXISTS "file" (
	"id"	INTEGER NOT NULL,
	"path"	text NOT NULL,
	"name"	text NOT NULL,
	"extension"	varchar(3) NOT NULL,
	"size"	integer NOT NULL,
	"title"	text,
	"publisher"	text,
	"publisher_id"	INTEGER,
	"creator"	text,
	"subject"	text,
	"language"	text,
	"description"	text,
	"date_created"	datetime NOT NULL,
	"date_modified"	datetime NOT NULL,
	"date_accessed"	datetime,
	"rating"	integer,
	"hash"	varchar(64) NOT NULL, apple_books boolean, series text, series_id INTEGER,
	PRIMARY KEY("id")
);
CREATE INDEX "file_date_accessed" ON "file" (
	"date_accessed"
);
CREATE INDEX "file_language" ON "file" (
	"language"
);
CREATE UNIQUE INDEX "file_hash" ON "file" (
	"hash"
);
CREATE UNIQUE INDEX "file_path" ON "file" (
	"path"
);
CREATE INDEX "file_extension" ON "file" (
	"extension"
);
CREATE VIEW bookmark_view AS SELECT
		bookmark.id,
		file.id as file_id,
		bookmark.title,
		bookmark.section,
		file.name,
		file.title as file_title,
		file.creator,
		file.subject,
		file.publisher
		FROM bookmark
		INNER JOIN file ON file.id = bookmark.file_id
/* bookmark_view(id,file_id,title,section,name,file_title,creator,subject,publisher) */;
sqlite>`

**Comment by stephenafamo** [comment]
I think it is possible that you are generating the models wrongly because the SQLite driver to sqlboiler is `sqlite3` not `sqlite`

Here are the commands I used to generate the models.

```shell
go install github.com/volatiletech/sqlboiler/v4
go install github.com/volatiletech/sqlboiler-sqlite3
go run github.com/volatiletech/sqlboiler/v4 sqlite3
```

After this generation, I tried to insert using the snippet in my earlier comment and it worked just fine for me.

Can you try again with the correct driver?

**Comment by gennaios** [comment]
thanks for continued help. same error:

```
 models: unable to insert into file: near "RETURNING": syntax error : goroutine 1 [running]:
runtime/debug.Stack()
	/opt/homebrew/opt/go/libexec/src/runtime/debug/stack.go:24 +0x88
github.com/deanishe/awgo.(*Workflow).Run.func2(0x1400000db00)
	/Users/gary/go/pkg/mod/github.com/deanishe/awgo@v0.22.1/workflow.go:343 +0xf0
panic({0x1037ad320, 0x1400000e390})
	/opt/homebrew/opt/go/libexec/src/runtime/panic.go:1038 +0x21c
jnana/internal/files.New(0x1400000e6d8, {0x16ef3b4db, 0xd3})
	./alfred-jnana/internal/files/files.go:197 +0x8c4
jnana/internal/files.Get(0x1400000e6d8, {0x16ef3b4db, 0xd3}, 0x1)
	./alfred-jnana/internal/files/files.go:82 +0x3e8
jnana/internal/bookmarks.ForFile(0x1400000e6d8, {0x16ef3b4db, 0xd3}, {0x14000024a20, 0x5c})
	./alfred-jnana/internal/bookmarks/bookmarks.go:31 +0x64
main.bookmarksForFile({0x16ef3b4db, 0xd3})
	./alfred-jnana/cmd/jnana/jnana.go:153 +0x4c
main.runCommand()
	./alfred-jnana/cmd/jnana/jnana.go:714 +0x420
main.run()
	./alfred-jnana/cmd/jnana/jnana.go:768 +0x114
github.com/deanishe/awgo.(*Workflow).Run(0x1400000db00, 0x1037da908)
	/Users/gary/go/pkg/mod/github.com/deanishe/awgo@v0.22.1/workflow.go:357 +0x310
main.main()
	./alfred-jnana/cmd/jnana/jnana.go:773 +0x3c
```

**Comment by stephenafamo** [comment]
Can you add `boil.DebugMode = true` and log the SQL queries being generated?

Since the error message says `syntax error` my guess is that one of the parameters you're trying to insert is badly formatted

**Comment by gennaios** [comment]
The output:

```
INSERT INTO "file" ("path","name","extension","size","title","publisher","publisher_id","creator","subject","language","description","date_created","date_modified","date_accessed","rating","hash","apple_books","series","series_id") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING "id"
[./Library/Mobile Documents/3L68KQB4HG~com~readdle~CommonDocuments/Documents/./Greek Myth and Religion - Albert Harvey, Henrichs Yunis (De Gruyter).pdf Greek Myth and Religion - Albert Harvey, Henrichs Yunis (De Gruyter).pdf pdf 2650558 {Greek Myth and Religion true} { true} {0 false} {Albert Henrichs;Harvey Yunis; true} { true} { false} { false} 2021-04-06 08:15:08.402 +0000 UTC 2021-04-06 08:15:08.411 +0000 UTC {2022-01-24 01:29:16.642 +0000 UTC true} {0 false} 10aede4925701c780ed6b91c5058dbbbf393cd9cd54a153d4c1701a8e9e230c1 {false false} { false} {0 false}]
17:29:41 ------------------ FATAL ERROR -------------------
17:29:41 models: unable to insert into file: near "RETURNING": syntax error : goroutine 1 [running]:
runtime/debug.Stack()
	/opt/homebrew/opt/go/libexec/src/runtime/debug/stack.go:24 +0x88
github.com/deanishe/awgo.(*Workflow).Run.func2(0x140001099e0)
	./go/pkg/mod/github.com/deanishe/awgo@v0.22.1/workflow.go:343 +0xf0
panic({0x105069320, 0x1400000e150})
	/opt/homebrew/opt/go/libexec/src/runtime/panic.go:1038 +0x21c
jnana/internal/files.New(0x140000b46c0, {0x16d67f503, 0xaa})
	../alfred-jnana/internal/files/files.go:198 +0x940
jnana/internal/files.Get(0x140000b46c0, {0x16d67f503, 0xaa}, 0x1)
	../alfred-jnana/internal/files/files.go:82 +0x3e8
jnana/internal/bookmarks.ForFile(0x140000b46c0, {0x16d67f503, 0xaa}, {0x1400008e960, 0x5c})
	../alfred-jnana/internal/bookmarks/bookmarks.go:31 +0x64
main.bookmarksForFile({0x16d67f503, 0xaa})
	../alfred-jnana/cmd/jnana/jnana.go:153 +0x4c
main.runCommand()
	../alfred-jnana/cmd/jnana/jnana.go:714 +0x420
main.run()
	../alfred-jnana/cmd/jnana/jnana.go:768 +0x114
github.com/deanishe/awgo.(*Workflow).Run(0x140001099e0, 0x105096908)
	./go/pkg/mod/github.com/deanishe/awgo@v0.22.1/workflow.go:357 +0x310
main.main()
	../alfred-jnana/cmd/jnana/jnana.go:773 +0x3c
```

I haven't tried to yet interpret the meanings of booleans true/false. publisher_id as 0, false seems like it should be null.

For now, the working raw SQL I've been using:

```
	_, _ = queries.Raw("INSERT INTO file (path, name, extension, size, title, publisher, creator, subject, date_created, date_modified, date_accessed, hash) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
		book,
		filepath.Base(book),
		strings.ToLower(filepath.Ext(book)[1:]),
		stat.Size(),
		null.StringFrom(f.Title),
		null.StringFrom(f.Publisher),
		null.StringFrom(f.Creator),
		null.StringFrom(f.Subject),
		dateCreated,
		dateModified,
		null.TimeFrom(t.AccessTime().UTC().Truncate(time.Millisecond)),
		hash).Exec(db.Db)
```

**Comment by stephenafamo** [comment]
Can you check what version your SQLite DB was created with by doing:

`SELECT sqlite_source_id();`

**Comment by gennaios** [comment]
You you think that would have effect?

`2022-01-06 13:25:41 872ba256cbf61d9290b571c0e6d82a20c224ca3ad82971edc46b29818d5d17a0`

The database was created long ago, but occassionally I run `vacuum into [filename]` to create a new file. One thing comes to mind. The page_size is non-standard: 16384 to match my platform, macOS arm64.

**Comment by stephenafamo** [comment]
I was thinking if maybe the DB was created with a much older version of sqlite, but this is the most recent version, same as mine.

I am also on macOS arm64, but I did not manually tweak the page size.

Honestly, I have no idea why this is happening for you. We have pretty much the same setup and environment, and I cannot reproduce this at all.

**Comment by gennaios** [comment]
Then perhaps you might be open to trying to compile the workflow and give it a try? It is an Alfred workflow, that indexes EPUB + PDF and allows one to search and navigate such by TOC titles (Preview + calibre epub reader). As it uses a module that I think verifies if Alfred is installed, running it from command-line, if you want to give it a try, variables are expected:

```
export alfred_workflow_bundleid="io.github.gennaios.jnana"
export alfred_workflow_cache="$HOME/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/io.github.gennaios.jnana"
export alfred_workflow_data="$HOME/Library/Application Support/Alfred/Workflow Data/io.github.gennaios.jnana"

# Expected by jnana
export alfred_workflow_version="0.1"
export alfred_workflow_name="jnana"

# export alfred_debug="1"
export alfred_preferences="$HOME/Library/Application Support/Alfred/Alfred.alfredpreferences"⏎
```

`./jnana bm [path to file]` should  be enough to try to create the db, and file/bookmark(toc) entries for such. It's been a while since I've tested init/setup on a new install so it's possible something might not work. 

If sometime you're willing to. I can also provide a compiled workflow if that's easier and you're up for it.

**Comment by stephenafamo** [comment]
Honestly, I don't use Alfred and I'm reluctant to set all this up to test this really specific bug.

But does this mean that the SQLite DB is managed by Alfred?

**Comment by gennaios** [comment]
Alfred merely provides environment variables such as cache and workflow storage folders, e.g. where to store the DB. One included module depends on such variables, and also provides methods to easily output results to console as JSON as expected by Alfred.

Testing the above listed variables, one can set the data folder to for example /tmp, and merely run the binary from the command line:

`export alfred_workflow_data="/tmp"`

If you're willing to give it a try. No need to install Alfred. Yet using raw SQL for record creation works fine and I'm ok with continuing to use such.
