### ISSUE TITLE
qm.Load() does not work when using .Bind() with an embedded struct

### ISSUE THREAD

**Issue by evanrolfe** [volatiletech/sqlboiler#1158]
SqlBoiler seems incapable of using `.Load()` to eager load a relationship when using `.Bind()` along with an embedded struct i.e. `PetWithStats` in the code below.

#### Versions
`SQLBoiler v4.11.0` and `mysql:5.7`

#### Code
```go
package main

import (
	"context"
	"fmt"

	"github.com/evanrolfe/sqlboiler_bug/internal/models"
	_ "github.com/go-sql-driver/mysql"
	"github.com/jmoiron/sqlx"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
)

type PetWithStats struct {
	models.Pet      `boil:",bind"`
	NumberOfFriends int64 `boil:"number_of_friends"`
	NumberOfEnemies int64 `boil:"number_of_enemies"`
}

func main() {
	db, err := sqlx.Connect("mysql", "...")
	if err != nil {
		fmt.Printf("failed connecting to the database: %w\n", err)
		return
	}
	ctx := context.Background()

	query := []qm.QueryMod{
		qm.Select("p.*"),
		qm.Select("(SELECT COUNT(*) FROM pets p2 WHERE p2.animal_id <> p.animal_id) AS number_of_friends"),
		qm.Select("(SELECT COUNT(*) FROM pets p2 WHERE p2.animal_id = p.animal_id) AS number_of_enemies"),
		qm.From(models.TableNames.Pets + " as p"),
		qm.Load(models.PetRels.Animal),
	}

	pets := []*PetWithStats{}
	err = models.NewQuery(query...).Bind(ctx, db, &pets)
	if err != nil {
		fmt.Printf("failed query: %w\n", err)
		return
	}

	for _, pet := range pets {
		fmt.Println(pet.ID, " ", pet.Name, "(", pet.R.Animal.Name, ")")
	}
}
```

#### Database Schema
```sql 
CREATE TABLE animals (
     id MEDIUMINT NOT NULL AUTO_INCREMENT,
     name CHAR(30) NOT NULL,
     PRIMARY KEY (id)
);

CREATE TABLE pets (
     id MEDIUMINT NOT NULL AUTO_INCREMENT,
     name CHAR(30) NOT NULL,
     animal_id MEDIUMINT NOT NULL,
     PRIMARY KEY (id),
     KEY `fk_pets_animal_id` (`animal_id`),
     CONSTRAINT `fk_pets_animal_id` FOREIGN KEY (`animal_id`) REFERENCES `animals` (`id`)
);

INSERT INTO animals (name) VALUES ('dog'),('cat'),('snake'),('bird'),('tiger');

INSERT INTO pets (name, animal_id) VALUES ('Alfie', 1),('Ruby', 1),('Felix', 2),('Bubbles', 2),('Monty',3);
```

#### What I expected to happen
I expected the code above to run and print each `pet` row along with its `animal.name`.

#### What actually happened
It panicked with this output:
```
panic: interface conversion: interface {} is *[]*main.PetWithStats, not *[]*models.Pet

goroutine 1 [running]:
github.com/evanrolfe/sqlboiler_bug/internal/models.petL.LoadAnimal({}, {0x13d77f8, 0xc00001a088}, {0x1c71518, 0xc0001a16e0}, 0x0, {0x12e3240?, 0xc00000e300?}, {0x0, 0x0})
	/Users/erolfe/Code/sqlboiler-bug/internal/models/pets.go:399 +0x965
reflect.Value.call({0xc00012aa00?, 0xc000011558?, 0xf0?}, {0x1342258, 0x4}, {0xc000136c30, 0x6, 0x78?})
	/usr/local/Cellar/go/1.18.1/libexec/src/reflect/value.go:556 +0x845
reflect.Value.Call({0xc00012aa00?, 0xc000011558?, 0xc00001b108?}, {0xc000136c30, 0x6, 0xa})
	/usr/local/Cellar/go/1.18.1/libexec/src/reflect/value.go:339 +0xbf
github.com/volatiletech/sqlboiler/v4/queries.loadRelationshipState.callLoadFunction({{0x13d77f8, 0xc00001a088}, {0x13d7490, 0xc0001a16e0}, 0xc0001a1950, {0xc000013470, 0x1, 0x1}, 0x0}, 0x0, ...)
	/Users/erolfe/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.11.0/queries/eager_load.go:195 +0xb72
github.com/volatiletech/sqlboiler/v4/queries.loadRelationshipState.loadRelationships({{0x13d77f8, 0xc00001a088}, {0x13d7490, 0xc0001a16e0}, 0xc0001a1950, {0xc000013470, 0x1, 0x1}, 0x0}, 0x0, ...)
	/Users/erolfe/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.11.0/queries/eager_load.go:106 +0x3b4
github.com/volatiletech/sqlboiler/v4/queries.eagerLoad({0x13d77f8?, 0xc00001a088?}, {0x13d7490?, 0xc0001a16e0?}, {0xc000013360, 0x1, 0xc00018fd38?}, 0x0, {0x12e3240, 0xc00000e300}, ...)
	/Users/erolfe/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.11.0/queries/eager_load.go:62 +0x1cb
github.com/volatiletech/sqlboiler/v4/queries.(*Query).Bind(0xc0001a6600, {0x13d77f8, 0xc00001a088}, {0x13d7490?, 0xc0001a16e0}, {0x12e3240, 0xc00000e300})
	/Users/erolfe/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.11.0/queries/reflect.go:155 +0x27c
main.main()
	/Users/erolfe/Code/sqlboiler-bug/main.go:40 +0x36e
exit status 2
```

If I change the line `pets := []*PetWithStats{}` to `pets := []*models.Pet{}` then the code works fine, but it means that I can't access the extra SELECT values from the query.

Thanks, Evan.

**Comment by stephenafamo** [comment]
Yep... this is a known old issue.

We are looking at rewriting a lot of the query builder to make it easier to support this, but that would likely introduce breaking changes and can only be in a new major version

**Comment by optiman** [comment]
@evanrolfe Check if this works for your case #1160

**Comment by stephenafamo** [comment]
Merged and released. Thank you @optiman

**Comment by evanrolfe** [comment]
Thank you both!!!
