### ISSUE TITLE
Bug when binding to *struct in struct

### ISSUE THREAD

**Issue by atzedus** [volatiletech/sqlboiler#1326]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
4.15.0

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
```go
	type Person struct {
		Name string `boil:"name"`
	}

	type Account struct {
		*Person `boil:",bind"`
	}

	var account Account

	_ = bmodels.NewQuery(
		qm.Select(`'Joe' as "person.name"`),
		qm.From("(SELECT 1) as fake_table"),
	).Bind(ctx, db, &account)

	fmt.Println(account.Person.Name)
```

This produces runtime panic error:
```
panic: reflect: call of reflect.Value.Field on zero Value

goroutine 1 [running]:
reflect.Value.Field({0x0?, 0x0?, 0x4000647258?}, 0x7473a8?)
	/usr/local/go/src/reflect/value.go:1278 +0xec
github.com/volatiletech/sqlboiler/v4/queries.ptrFromMapping({0x1839360?, 0x4000520f30?, 0x40006472c8?}, 0xff0000, 0x1)
	/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.15.0/queries/reflect.go:369 +0xe4
github.com/volatiletech/sqlboiler/v4/queries.PtrsFromMapping({0x1839360?, 0x4000520f30?, 0x1?}, {0x40002a0fc0, 0x1, 0x2e96da0?})
	/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.15.0/queries/reflect.go:335 +0x90
github.com/volatiletech/sqlboiler/v4/queries.bind(0x16ceee0?, {0x16ceee0, 0x4000520f30}, {0x1ee49f0, 0x1839360}, {0x980014?, 0x0?}, 0x0)
	/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.15.0/queries/reflect.go:250 +0x2bc
github.com/volatiletech/sqlboiler/v4/queries.(*Query).Bind(0x40006a5500, {0x1ec7240, 0x400070a550}, {0x1ec4400?, 0x400040a460}, {0x16ceee0, 0x4000520f30})
	/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.15.0/queries/reflect.go:143 +0xcc
```

### Further information. What did you do, what did you expect?
Expected success run with "Joe" string output.

How it can be fixed now: preinit destination struct with zero valued struct, like:
```go
account := Account{
Person: &Person{}
}
```

Second variant to fix it is use struct without pointer, like:
```go
	type Account struct {
		Person Person `boil:",bind"`
	}
```

According to documentation: https://pkg.go.dev/github.com/volatiletech/sqlboiler/v4/queries#Bind this must work.

Is this bug or feature?

**Comment by ckcr4lyf** [comment]
Ran into the same problem. I mitigated by going with the second variant, i.e. to use struct without Pointer.
