### ISSUE TITLE
slice bound out of range (Windows)

### ISSUE THREAD

**Issue by louis77** [volatiletech/sqlboiler#314]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v3.0.0-rc4

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
sqlboiler.exe psql

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)
using driver: C:\Users\lwbbr\go\bin\sqlboiler-psql.exe
```
{"config":{"driver_name":"psql","driver_config":{"blacklist":null,"dbname":"XXX","host":"XXX","pass":"XXX","port":12345,"schema":"public","sslmode":"require","user":"XXX","whitelist":["availabilities","bookings","groups"]},"pkg_name":"models","out_folder":"models","debug":true,"struct_tag_casing":"snake","imports":{"all":{"Standard":["\"database/sql\"","\"fmt\"","\"reflect\"","\"strconv\"","\"strings\"","\"sync\"","\"time\"","\"context\""],"ThirdParty":["\"github.com/pkg/errors\"","\"github.com/volatiletech/sqlboiler/boil\"","\"github.com/volatiletech/sqlboiler/queries\"","\"github.com/volatiletech/sqlboiler/queries/qm\"","\"github.com/volatiletech/sqlboiler/strmangle\""]},"test":{"Standard":["\"bytes\"","\"reflect\"","\"testing\"","\"context\""],"ThirdParty":["\"github.com/volatiletech/sqlboiler/boil\"","\"github.com/volatiletech/sqlboiler/queries\"","\"github.com/volatiletech/sqlboiler/randomize\"","\"github.com/volatiletech/sqlboiler/strmangle\""]},"singleton":{"boil_queries":{"Standard":null,"ThirdParty":["\"github.com/volatiletech/sqlboiler/drivers\"","\"github.com/volatiletech/sqlboiler/queries\"","\"github.com/volatiletech/sqlboiler/queries/qm\""]},"boil_types":{"Standard":["\"strconv\""],"ThirdParty":["\"github.com/pkg/errors\"","\"github.com/volatiletech/sqlboiler/boil\"","\"github.com/volatiletech/sqlboiler/strmangle\""]},"psql_upsert":{"Standard":["\"fmt\"","\"strings\""],"ThirdParty":["\"github.com/volatiletech/sqlboiler/drivers\"","\"github.com/volatiletech/sqlboiler/strmangle\""]}},"test_singleton":{"boil_main_test":{"Standard":["\"database/sql\"","\"flag\"","\"fmt\"","\"math/rand\"","\"os\"","\"path/filepath\"","\"strings\"","\"testing\"","\"time\""],"ThirdParty":["\"github.com/spf13/viper\"","\"github.com/volatiletech/sqlboiler/boil\""]},"boil_queries_test":{"Standard":["\"bytes\"","\"fmt\"","\"io\"","\"io/ioutil\"","\"math/rand\"","\"regexp\""],"ThirdParty":["\"github.com/volatiletech/sqlboiler/boil\""]},"boil_suites_test":{"Standard":["\"testing\""],"ThirdParty":null},"psql_main_test":{"Standard":["\"bytes\"","\"database/sql\"","\"fmt\"","\"io\"","\"io/ioutil\"","\"os\"","\"os/exec\"","\"regexp\"","\"strings\""],"ThirdParty":["\"github.com/kat-co/vala\"","_ \"github.com/lib/pq\"","\"github.com/pkg/errors\"","\"github.com/spf13/viper\"","\"github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql/driver\"","\"github.com/volatiletech/sqlboiler/randomize\""]},"psql_suites_test":{"Standard":["\"testing\""],"ThirdParty":[]}},"based_on_type":{"null.Bool":{"Standard":[],"ThirdParty":["\"gopkg.in/volatiletech/null.v7\""]},"null.Bytes":{"Standard":[],"ThirdParty":["\"gopkg.in/volatiletech/null.v7\""]},"null.Float32":{"Standard":[],"ThirdParty":["\"gopkg.in/volatiletech/null.v7\""]},"null.Float64":{"Standard":[],"ThirdParty":["\"gopkg.in/volatiletech/null.v7\""]},"null.Int":{"Standard":[],"ThirdParty":["\"gopkg.in/volatiletech/null.v7\""]},"null.Int16":{"Standard":[],"ThirdParty":["\"gopkg.in/volatiletech/null.v7\""]},"null.Int32":{"Standard":[],"ThirdParty":["\"gopkg.in/volatiletech/null.v7\""]},"null.Int64":{"Standard":[],"ThirdParty":["\"gopkg.in/volatiletech/null.v7\""]},"null.Int8":{"Standard":[],"ThirdParty":["\"gopkg.in/volatiletech/null.v7\""]},"null.JSON":{"Standard":[],"ThirdParty":["\"gopkg.in/volatiletech/null.v7\""]},"null.String":{"Standard":[],"ThirdParty":["\"gopkg.in/volatiletech/null.v7\""]},"null.Time":{"Standard":[],"ThirdParty":["\"gopkg.in/volatiletech/null.v7\""]},"null.Uint":{"Standard":[],"ThirdParty":["\"gopkg.in/volatiletech/null.v7\""]},"null.Uint16":{"Standard":[],"ThirdParty":["\"gopkg.in/volatiletech/null.v7\""]},"null.Uint32":{"Standard":[],"ThirdParty":["\"gopkg.in/volatiletech/null.v7\""]},"null.Uint64":{"Standard":[],"ThirdParty":["\"gopkg.in/volatiletech/null.v7\""]},"null.Uint8":{"Standard":[],"ThirdParty":["\"gopkg.in/volatiletech/null.v7\""]},"pgeo.Box":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.Circle":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.Line":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.Lseg":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullBox":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullCircle":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullLine":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullLseg":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullPath":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullPoint":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullPolygon":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.Path":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.Point":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.Polygon":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"time.Time":{"Standard":["\"time\""],"ThirdParty":[]},"types.BoolArray":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.BytesArray":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.Decimal":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.DecimalArray":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.Float64Array":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.Hstore":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.Int64Array":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.JSON":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.NullDecimal":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.StringArray":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]}}},"aliases":{"tables":{"bookings":{"columns":{"group":"GroupID"}}}}},"driver_config":{"blacklist":null,"dbname":"XXX","host":"XXX","pass":"XXX","port":12345,"schema":"public","sslmode":"require","user":"XXX","whitelist":["availabilities","bookings","groups"]},"tables":[{"name":"availabilities","schema_name":"","columns":[{"name":"id","type":"int","db_type":"integer","default":"nextval('availabilities_id_seq'::regclass)","nullable":false,"unique":true,"validated":false,"arr_type":null,"udt_name":"int4","full_db_type":"","auto_generated":false},{"name":"accommodation","type":"string","db_type":"text","default":"","nullable":false,"unique":false,"validated":false,"arr_type":null,"udt_name":"text","full_db_type":"","auto_generated":false},{"name":"provider","type":"string","db_type":"text","default":"","nullable":false,"unique":false,"validated":false,"arr_type":null,"udt_name":"text","full_db_type":"","auto_generated":false},{"name":"arrival","type":"types.Int64Array","db_type":"ARRAYinteger","default":"'{}'::integer[]","nullable":false,"unique":false,"validated":false,"arr_type":"integer","udt_name":"_int4","full_db_type":"","auto_generated":false},{"name":"free","type":"types.Int64Array","db_type":"ARRAYinteger","default":"'{}'::integer[]","nullable":false,"unique":false,"validated":false,"arr_type":"integer","udt_name":"_int4","full_db_type":"","auto_generated":false},{"name":"minstay","type":"types.Int64Array","db_type":"ARRAYinteger","default":"'{}'::integer[]","nullable":false,"unique":false,"validated":false,"arr_type":"integer","udt_name":"_int4","full_db_type":"","auto_generated":false},{"name":"ts","type":"null.Time","db_type":"timestamp with time zone","default":"now()","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"timestamptz","full_db_type":"","auto_generated":false}],"p_key":{"name":"availabilities_pkey","columns":["id"]},"f_keys":null,"is_join_table":false,"to_one_relationships":null,"to_many_relationships":null},{"name":"bookings","schema_name":"","columns":[{"name":"engine","type":"string","db_type":"character varying","default":"","nullable":false,"unique":false,"validated":false,"arr_type":null,"udt_name":"varchar","full_db_type":"","auto_generated":false},{"name":"group","type":"string","db_type":"character varying","default":"","nullable":false,"unique":false,"validated":false,"arr_type":null,"udt_name":"varchar","full_db_type":"","auto_generated":false},{"name":"provider","type":"string","db_type":"text","default":"","nullable":false,"unique":false,"validated":false,"arr_type":null,"udt_name":"text","full_db_type":"","auto_generated":false},{"name":"checkin","type":"null.Time","db_type":"date","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"date","full_db_type":"","auto_generated":false},{"name":"checkout","type":"null.Time","db_type":"date","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"date","full_db_type":"","auto_generated":false},{"name":"booked","type":"null.Time","db_type":"date","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"date","full_db_type":"","auto_generated":false},{"name":"type","type":"null.String","db_type":"text","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"text","full_db_type":"","auto_generated":false},{"name":"currency","type":"null.String","db_type":"text","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"text","full_db_type":"","auto_generated":false},{"name":"children","type":"null.Int","db_type":"integer","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"int4","full_db_type":"","auto_generated":false},{"name":"adults","type":"null.Int","db_type":"integer","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"int4","full_db_type":"","auto_generated":false},{"name":"price","type":"null.Float32","db_type":"real","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"float4","full_db_type":"","auto_generated":false},{"name":"external_id","type":"null.String","db_type":"text","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"text","full_db_type":"","auto_generated":false},{"name":"status","type":"null.String","db_type":"text","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"text","full_db_type":"","auto_generated":false},{"name":"reference","type":"null.JSON","db_type":"jsonb","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"jsonb","full_db_type":"","auto_generated":false},{"name":"createdAt","type":"null.Time","db_type":"timestamp with time zone","default":"CURRENT_TIMESTAMP","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"timestamptz","full_db_type":"","auto_generated":false},{"name":"updatedAt","type":"null.Time","db_type":"timestamp with time zone","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"timestamptz","full_db_type":"","auto_generated":false},{"name":"reference_name","type":"null.String","db_type":"text","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"text","full_db_type":"","auto_generated":false},{"name":"reference_external_id","type":"null.String","db_type":"text","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"text","full_db_type":"","auto_generated":false},{"name":"id","type":"int","db_type":"integer","default":"nextval('bookings_id_seq'::regclass)","nullable":false,"unique":true,"validated":false,"arr_type":null,"udt_name":"int4","full_db_type":"","auto_generated":false}],"p_key":{"name":"bookings_pkey","columns":["id"]},"f_keys":[{"table":"bookings","name":"fk_group","column":"group","nullable":false,"unique":false,"foreign_table":"groups","foreign_column":"id","foreign_column_nullable":false,"foreign_column_unique":true}],"is_join_table":false,"to_one_relationships":null,"to_many_relationships":null},{"name":"groups","schema_name":"","columns":[{"name":"id","type":"string","db_type":"character varying","default":"","nullable":false,"unique":true,"validated":false,"arr_type":null,"udt_name":"varchar","full_db_type":"","auto_generated":false},{"name":"name","type":"string","db_type":"text","default":"","nullable":false,"unique":false,"validated":false,"arr_type":null,"udt_name":"text","full_db_type":"","auto_generated":false},{"name":"email","type":"null.String","db_type":"text","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"text","full_db_type":"","auto_generated":false},{"name":"createdAt","type":"null.Time","db_type":"timestamp with time zone","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"timestamptz","full_db_type":"","auto_generated":false},{"name":"updatedAt","type":"null.Time","db_type":"timestamp with time zone","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"timestamptz","full_db_type":"","auto_generated":false}],"p_key":{"name":"groups_pkey","columns":["id"]},"f_keys":null,"is_join_table":false,"to_one_relationships":null,"to_many_relationships":[{"name":"fk_group","table":"groups","column":"id","nullable":false,"unique":true,"foreign_table":"bookings","foreign_column":"group","foreign_column_nullable":false,"foreign_column_unique":false,"to_join_table":false,"join_table":"","join_local_fkey_name":"","join_local_column":"","join_local_column_nullable":false,"join_local_column_unique":false,"join_foreign_fkey_name":"","join_foreign_column":"","join_foreign_column_nullable":false,"join_foreign_column_unique":false}]}],"templates":[{"name":"templates/00_struct.go.tpl","loader":"asset:templates/00_struct.go.tpl"},{"name":"templates/01_types.go.tpl","loader":"asset:templates/01_types.go.tpl"},{"name":"templates/02_hooks.go.tpl","loader":"asset:templates/02_hooks.go.tpl"},{"name":"templates/03_finishers.go.tpl","loader":"asset:templates/03_finishers.go.tpl"},{"name":"templates/04_relationship_to_one.go.tpl","loader":"asset:templates/04_relationship_to_one.go.tpl"},{"name":"templates/05_relationship_one_to_one.go.tpl","loader":"asset:templates/05_relationship_one_to_one.go.tpl"},{"name":"templates/06_relationship_to_many.go.tpl","loader":"asset:templates/06_relationship_to_many.go.tpl"},{"name":"templates/07_relationship_to_one_eager.go.tpl","loader":"asset:templates/07_relationship_to_one_eager.go.tpl"},{"name":"templates/08_relationship_one_to_one_eager.go.tpl","loader":"asset:templates/08_relationship_one_to_one_eager.go.tpl"},{"name":"templates/09_relationship_to_many_eager.go.tpl","loader":"asset:templates/09_relationship_to_many_eager.go.tpl"},{"name":"templates/10_relationship_to_one_setops.go.tpl","loader":"asset:templates/10_relationship_to_one_setops.go.tpl"},{"name":"templates/11_relationship_one_to_one_setops.go.tpl","loader":"asset:templates/11_relationship_one_to_one_setops.go.tpl"},{"name":"templates/12_relationship_to_many_setops.go.tpl","loader":"asset:templates/12_relationship_to_many_setops.go.tpl"},{"name":"templates/13_all.go.tpl","loader":"asset:templates/13_all.go.tpl"},{"name":"templates/14_find.go.tpl","loader":"asset:templates/14_find.go.tpl"},{"name":"templates/15_insert.go.tpl","loader":"asset:templates/15_insert.go.tpl"},{"name":"templates/16_update.go.tpl","loader":"asset:templates/16_update.go.tpl"},{"name":"templates/17_upsert.go.tpl","loader":"base64:(sha256 of content): 8263cfaa595591606e435813bd5d8424db61b98b6d29936599cedc4e176660a5"},{"name":"templates/18_delete.go.tpl","loader":"asset:templates/18_delete.go.tpl"},{"name":"templates/19_reload.go.tpl","loader":"asset:templates/19_reload.go.tpl"},{"name":"templates/20_exists.go.tpl","loader":"asset:templates/20_exists.go.tpl"},{"name":"templates/21_auto_timestamps.go.tpl","loader":"asset:templates/21_auto_timestamps.go.tpl"},{"name":"templates/singleton/boil_queries.go.tpl","loader":"asset:templates/singleton/boil_queries.go.tpl"},{"name":"templates/singleton/boil_table_names.go.tpl","loader":"asset:templates/singleton/boil_table_names.go.tpl"},{"name":"templates/singleton/boil_types.go.tpl","loader":"asset:templates/singleton/boil_types.go.tpl"},{"name":"templates/singleton/psql_upsert.go.tpl","loader":"base64:(sha256 of content): cb25b2a17877de034695accfb0a1f5f11437114d5f919062c792efee53cbb25f"},{"name":"templates_test/00_types.go.tpl","loader":"asset:templates_test/00_types.go.tpl"},{"name":"templates_test/all.go.tpl","loader":"asset:templates_test/all.go.tpl"},{"name":"templates_test/delete.go.tpl","loader":"asset:templates_test/delete.go.tpl"},{"name":"templates_test/exists.go.tpl","loader":"asset:templates_test/exists.go.tpl"},{"name":"templates_test/find.go.tpl","loader":"asset:templates_test/find.go.tpl"},{"name":"templates_test/finishers.go.tpl","loader":"asset:templates_test/finishers.go.tpl"},{"name":"templates_test/hooks.go.tpl","loader":"asset:templates_test/hooks.go.tpl"},{"name":"templates_test/insert.go.tpl","loader":"asset:templates_test/insert.go.tpl"},{"name":"templates_test/relationship_one_to_one.go.tpl","loader":"asset:templates_test/relationship_one_to_one.go.tpl"},{"name":"templates_test/relationship_one_to_one_setops.go.tpl","loader":"asset:templates_test/relationship_one_to_one_setops.go.tpl"},{"name":"templates_test/relationship_to_many.go.tpl","loader":"asset:templates_test/relationship_to_many.go.tpl"},{"name":"templates_test/relationship_to_many_setops.go.tpl","loader":"asset:templates_test/relationship_to_many_setops.go.tpl"},{"name":"templates_test/relationship_to_one.go.tpl","loader":"asset:templates_test/relationship_to_one.go.tpl"},{"name":"templates_test/relationship_to_one_setops.go.tpl","loader":"asset:templates_test/relationship_to_one_setops.go.tpl"},{"name":"templates_test/reload.go.tpl","loader":"asset:templates_test/reload.go.tpl"},{"name":"templates_test/select.go.tpl","loader":"asset:templates_test/select.go.tpl"},{"name":"templates_test/singleton/boil_main_test.go.tpl","loader":"asset:templates_test/singleton/boil_main_test.go.tpl"},{"name":"templates_test/singleton/boil_queries_test.go.tpl","loader":"asset:templates_test/singleton/boil_queries_test.go.tpl"},{"name":"templates_test/singleton/boil_suites_test.go.tpl","loader":"asset:templates_test/singleton/boil_suites_test.go.tpl"},{"name":"templates_test/singleton/psql_main_test.go.tpl","loader":"base64:(sha256 of content): 473b063ee1f0281401d67450acb9eeac3f096030c2968aad15fc180358f8119f"},{"name":"templates_test/singleton/psql_suites_test.go.tpl","loader":"base64:(sha256 of content): 10c471afd916418b4bfce8bafdfa4d2c01d100e1b078ee7fd065f3a143ba3ce7"},{"name":"templates_test/types.go.tpl","loader":"asset:templates_test/types.go.tpl"},{"name":"templates_test/update.go.tpl","loader":"asset:templates_test/update.go.tpl"},{"name":"templates_test/upsert.go.tpl","loader":"base64:(sha256 of content): 519b35b1d2c50c1b0e341ff900b9ad23a8b48c497b295ff189838cd490bd1701"}]}
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/volatiletech/sqlboiler/boilingcore.(*State).initOutFolders(0xc04223a9c0, 0xc042252e00, 0x32, 0x32, 0x0, 0x0)
        C:/Users/lwbbr/go/src/github.com/volatiletech/sqlboiler/boilingcore/boilingcore.go:500 +0x50f
github.com/volatiletech/sqlboiler/boilingcore.New(0xc04216c8c0, 0x0, 0x0, 0x0)
        C:/Users/lwbbr/go/src/github.com/volatiletech/sqlboiler/boilingcore/boilingcore.go:104 +0x1e7
main.preRun(0xc04218a000, 0xc0421030a0, 0x1, 0x2, 0x0, 0x0)
        C:/Users/lwbbr/go/src/github.com/volatiletech/sqlboiler/main.go:201 +0xbfe
github.com/spf13/cobra.(*Command).execute(0xc04218a000, 0xc042072090, 0x2, 0x3, 0xc04218a000, 0xc042072090)
        C:/Users/lwbbr/go/src/github.com/spf13/cobra/command.go:751 +0x51d
github.com/spf13/cobra.(*Command).ExecuteC(0xc04218a000, 0xc0420aeb00, 0x0, 0xc042064500)
        C:/Users/lwbbr/go/src/github.com/spf13/cobra/command.go:852 +0x311
github.com/spf13/cobra.(*Command).Execute(0xc04218a000, 0x2, 0x2)
        C:/Users/lwbbr/go/src/github.com/spf13/cobra/command.go:800 +0x32
main.main()
        C:/Users/lwbbr/go/src/github.com/volatiletech/sqlboiler/main.go:117 +0x90a
```

### Further information. What did you do, what did you expect?
Did some debugging.
 boilingcore.go:496 is using `os.PathSeparator` which is '\\' (int 92) and not '/' as in t.Name ([templates/00_struct.go.tpl]), so splitting will not work. Why not use path.Split()?

**Comment by louis77** [comment]
Same issue on C:\Users\lwbbr\go\src\github.com\volatiletech\sqlboiler\boilingcore\output.go:299. 
When I replace both usages to "/" generation works.

**Comment by aarondl** [comment]
Hey @louis77. Thanks for reporting the bug. I'm working on it now.

This is the result of an attempt to maintain cross platform without being able to test on the other platform. Sorry about that :(

One of the reasons we can't use `path.Split` in these instances is because it's possible for the windows user to use the `--templates` flag that will end up giving us paths with `\` in them. I'm considering the best course of action. I should have a fix fairly shortly.

**Comment by aarondl** [comment]
Oh, and one more reason for the no `path.Split`. The only reason the paths are `/` to begin with is the bindata was generated on Linux. If it was generated by someone on Windows then they'd run into the same problem again.

**Comment by aarondl** [comment]
Hi @louis77. I've got a patch out. v3.0.0-rc5. It fixes several issues with Windows paths. I was able to generate models with and without tests, and also run the tests successfully. Hopefully it works for you. If not let me know. Closing this for now.
