### ISSUE TITLE
panic:  interface conversion: interface {} is string, not map[string]interface {}

### ISSUE THREAD

**Issue by msonawane** [volatiletech/sqlboiler#376]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

λ sqlboiler --version
SQLBoiler v3.0.0

λ sqlboiler psql -d
panic: interface conversion: interface {} is string, not map[string]interface {}

goroutine 1 [running]:
github.com/volatiletech/sqlboiler/boilingcore.ConvertAliases(0x87c640, 0xc042055ef0, 0x0)
        C:/Users/m/go/src/github.com/volatiletech/sqlboiler/boilingcore/config.go:72 +0xd7
main.preRun(0xc042172000, 0xc0420e9020, 0x1, 0x2, 0x0, 0x0)
        C:/Users/m/go/src/github.com/volatiletech/sqlboiler/main.go:180 +0x495
github.com/spf13/cobra.(*Command).execute(0xc042172000, 0xc04205c090, 0x2, 0x3, 0xc042172000, 0xc04205c090)
        C:/Users/m/go/src/github.com/spf13/cobra/command.go:751 +0x51d
github.com/spf13/cobra.(*Command).ExecuteC(0xc042172000, 0xc042098b00, 0x0, 0xc04204e500)
        C:/Users/m/go/src/github.com/spf13/cobra/command.go:852 +0x311
github.com/spf13/cobra.(*Command).Execute(0xc042172000, 0x2, 0x2)
        C:/Users/m/go/src/github.com/spf13/cobra/command.go:800 +0x32
main.main()
        C:/Users/m/go/src/github.com/volatiletech/sqlboiler/main.go:117 +0x90a

### Further information. What did you do, what did you expect?

Windows 10 followed readme to install version 3

**Comment by msonawane** [comment]
this seems to be due to cmder console app. problem does not appear in normal cmd window
