### ISSUE TITLE
Replace geography(POINT) type from string to orb.Point

### ISSUE THREAD

**Issue by iamtakingiteasy** [volatiletech/sqlboiler#484]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
    $ sqlboiler --version
    SQLBoiler v3.2.0

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
    $ sqlboiler psql --wipe -d | jq
    
    panic: import set should be map[string]interface{}

    goroutine 1 [running]:
    github.com/volatiletech/sqlboiler/boilingcore.ConvertTypeReplace(0x899e20, 0xc0000b6ea0, 0x899e20, 0xc0000b6ea0, 0x0)
        /home/go/pkg/mod/github.com/volatiletech/sqlboiler@v3.2.0+incompatible/boilingcore/config.go:194 +0x530
    main.preRun(0xc000177680, 0xc00016fec0, 0x1, 0x3, 0x0, 0x0)
        /home/go/pkg/mod/github.com/volatiletech/sqlboiler@v3.2.0+incompatible/main.go:181 +0x4cd
    github.com/spf13/cobra.(*Command).execute(0xc000177680, 0xc0000ae050, 0x3, 0x3, 0xc000177680, 0xc0000ae050)
        /home/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:751 +0x521
    github.com/spf13/cobra.(*Command).ExecuteC(0xc000177680, 0xc0000d2c00, 0xc000084700, 0x0)
        /home/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
    github.com/spf13/cobra.(*Command).Execute(0xc000177680, 0x2, 0x2)
        /home/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
    main.main()
        /home/go/pkg/mod/github.com/volatiletech/sqlboiler@v3.2.0+incompatible/main.go:117 +0x938

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

    create table locations (
      id          bigserial primary key,
      type        integer not null,
      name        text not null,
      description text,
      pos         geography(POINT,4326) not null
    );
    create index locations_pos_gix on locations using gist(pos);

### Further information. What did you do, what did you expect?

Using sqlboiler.yaml as:

    no-tests: true
    no-context: true
    psql:
      dbname: geo
      host: 10.252.0.21
      user: geo
      pass: geo
      sslmode: disable
      blacklist:
        - schema_migrations
        - geography_columns
        - geometry_columns
        - raster_columns
        - raster_overviews

    types:
      - match:
          type: "geography"
          nullable: true
        replace:
          type: "orb.Point"
        imports:
          third_party:
            - '"github.com/paulmach/orb"'

above panic is issued by sqlboiler, while i would expect (by looking at README.md) to generate the schema using `orb.Point` as model for at least `geography(POINT)` types instead of string.

**Comment by iamtakingiteasy** [comment]
Also none of this is adding import to `locations.go` file:

    imports:
      singleton:
        locations:
          third_party:
            - '"github.com/paulmach/orb"'
        '"locations"':
          third_party:
            - '"github.com/paulmach/orb"'
      locations:
        third_party:
          - '"github.com/paulmach/orb"'
      '"locations"':
        third_party:
          - '"github.com/paulmach/orb"'

This one however does, but does that for every file, leading to unused imports:

    imports:
      all:
        third_party:
          - '"github.com/paulmach/orb"'

**Comment by iamtakingiteasy** [comment]
The  `sqlboiler psql --wipe  -d` output (without all: version)

```
using driver: /home/go/bin/sqlboiler-psql
warning: incompatible data type detected: geography
{"config":{"driver_name":"psql","driver_config":{"blacklist":["schema_migrations","geography_columns","geometry_columns","raster_columns","raster_overviews"],"dbname":"geo","host":"10.252.0.21","pass":"geo","sslmode":"disable","user":"geo","whitelist":null},"pkg_name":"models","out_folder":"models","debug":true,"no_context":true,"no_tests":true,"wipe":true,"struct_tag_casing":"snake","imports":{"all":{"Standard":["\"database/sql\"","\"fmt\"","\"reflect\"","\"strconv\"","\"strings\"","\"sync\"","\"time\""],"ThirdParty":["\"github.com/pkg/errors\"","\"github.com/volatiletech/sqlboiler/boil\"","\"github.com/volatiletech/sqlboiler/queries\"","\"github.com/volatiletech/sqlboiler/queries/qm\"","\"github.com/volatiletech/sqlboiler/queries/qmhelper\"","\"github.com/volatiletech/sqlboiler/strmangle\""]},"test":{"Standard":["\"bytes\"","\"reflect\"","\"testing\""],"ThirdParty":["\"github.com/volatiletech/sqlboiler/boil\"","\"github.com/volatiletech/sqlboiler/queries\"","\"github.com/volatiletech/sqlboiler/randomize\"","\"github.com/volatiletech/sqlboiler/strmangle\""]},"singleton":{"\"locations\"":{"Standard":null,"ThirdParty":["\"github.com/paulmach/orb\""]},"locations":{"Standard":null,"ThirdParty":["\"github.com/paulmach/orb\""]},"psql_upsert":{"Standard":["\"fmt\"","\"strings\""],"ThirdParty":["\"github.com/volatiletech/sqlboiler/drivers\"","\"github.com/volatiletech/sqlboiler/strmangle\""]}},"test_singleton":{"boil_main_test":{"Standard":["\"database/sql\"","\"flag\"","\"fmt\"","\"math/rand\"","\"os\"","\"path/filepath\"","\"strings\"","\"testing\"","\"time\""],"ThirdParty":["\"github.com/spf13/viper\"","\"github.com/volatiletech/sqlboiler/boil\""]},"boil_queries_test":{"Standard":["\"bytes\"","\"fmt\"","\"io\"","\"io/ioutil\"","\"math/rand\"","\"regexp\""],"ThirdParty":["\"github.com/volatiletech/sqlboiler/boil\""]},"boil_suites_test":{"Standard":["\"testing\""],"ThirdParty":null},"psql_main_test":{"Standard":["\"bytes\"","\"database/sql\"","\"fmt\"","\"io\"","\"io/ioutil\"","\"os\"","\"os/exec\"","\"regexp\"","\"strings\""],"ThirdParty":["\"github.com/kat-co/vala\"","_ \"github.com/lib/pq\"","\"github.com/pkg/errors\"","\"github.com/spf13/viper\"","\"github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql/driver\"","\"github.com/volatiletech/sqlboiler/randomize\""]},"psql_suites_test":{"Standard":["\"testing\""],"ThirdParty":[]}},"based_on_type":{"\"geography\"":{"Standard":null,"ThirdParty":["\"github.com/paulmach/orb\""]},"\"orb.point\"":{"Standard":null,"ThirdParty":["\"github.com/paulmach/orb\""]},"geography":{"Standard":null,"ThirdParty":["\"github.com/paulmach/orb\""]},"null.Bool":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Bytes":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Float32":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Float64":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Int":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Int16":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Int32":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Int64":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Int8":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.JSON":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.String":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Time":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Uint":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Uint16":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Uint32":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Uint64":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Uint8":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"orb.point":{"Standard":null,"ThirdParty":["\"github.com/paulmach/orb\""]},"pgeo.Box":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.Circle":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.Line":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.Lseg":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullBox":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullCircle":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullLine":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullLseg":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullPath":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullPoint":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullPolygon":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.Path":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.Point":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.Polygon":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"time.Time":{"Standard":["\"time\""],"ThirdParty":[]},"types.BoolArray":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.BytesArray":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.Decimal":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.DecimalArray":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.Float64Array":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.Hstore":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.Int64Array":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.JSON":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.NullDecimal":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.StringArray":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]}}},"aliases":{"tables":{"locations":{"up_plural":"Locations","up_singular":"Location","down_plural":"locations","down_singular":"location","columns":{"description":"Description","id":"ID","name":"Name","pos":"Pos","type":"Type"}},"spatial_ref_sys":{"up_plural":"SpatialRefSys","up_singular":"SpatialRefSy","down_plural":"spatialRefSys","down_singular":"spatialRefSy","columns":{"auth_name":"AuthName","auth_srid":"AuthSrid","proj4text":"Proj4text","srid":"Srid","srtext":"Srtext"}}}},"type_replaces":[{"match":{"name":"pos","type":"","db_type":"","default":"","nullable":false,"unique":false,"validated":false,"arr_type":null,"udt_name":"geography","full_db_type":"","auto_generated":false},"replace":{"name":"","type":"orb.Point","db_type":"","default":"","nullable":false,"unique":false,"validated":false,"arr_type":null,"udt_name":"","full_db_type":"","auto_generated":false},"imports":{"Standard":null,"ThirdParty":null}}]},"driver_config":{"blacklist":["schema_migrations","geography_columns","geometry_columns","raster_columns","raster_overviews"],"dbname":"geo","host":"10.252.0.21","pass":"geo","sslmode":"disable","user":"geo","whitelist":null},"schema":"public","dialect":{"lq":34,"rq":34,"use_index_placeholders":true,"use_last_insert_id":false,"use_schema":false,"use_default_keyword":true,"use_auto_columns":false,"use_top_clause":false,"use_output_clause":false,"use_case_when_exists_clause":false},"tables":[{"name":"locations","schema_name":"","columns":[{"name":"id","type":"int64","db_type":"bigint","default":"nextval('locations_id_seq'::regclass)","nullable":false,"unique":true,"validated":false,"arr_type":null,"udt_name":"int8","full_db_type":"","auto_generated":false},{"name":"type","type":"int","db_type":"integer","default":"","nullable":false,"unique":false,"validated":false,"arr_type":null,"udt_name":"int4","full_db_type":"","auto_generated":false},{"name":"name","type":"string","db_type":"text","default":"","nullable":false,"unique":false,"validated":false,"arr_type":null,"udt_name":"text","full_db_type":"","auto_generated":false},{"name":"description","type":"null.String","db_type":"text","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"text","full_db_type":"","auto_generated":false},{"name":"pos","type":"orb.Point","db_type":"USER-DEFINED","default":"","nullable":false,"unique":false,"validated":false,"arr_type":null,"udt_name":"geography","full_db_type":"","auto_generated":false}],"p_key":{"name":"locations_pkey","columns":["id"]},"f_keys":null,"is_join_table":false,"to_one_relationships":null,"to_many_relationships":null},{"name":"spatial_ref_sys","schema_name":"","columns":[{"name":"srid","type":"int","db_type":"integer","default":"","nullable":false,"unique":true,"validated":false,"arr_type":null,"udt_name":"int4","full_db_type":"","auto_generated":false},{"name":"auth_name","type":"null.String","db_type":"character varying","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"varchar","full_db_type":"","auto_generated":false},{"name":"auth_srid","type":"null.Int","db_type":"integer","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"int4","full_db_type":"","auto_generated":false},{"name":"srtext","type":"null.String","db_type":"character varying","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"varchar","full_db_type":"","auto_generated":false},{"name":"proj4text","type":"null.String","db_type":"character varying","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"varchar","full_db_type":"","auto_generated":false}],"p_key":{"name":"spatial_ref_sys_pkey","columns":["srid"]},"f_keys":null,"is_join_table":false,"to_one_relationships":null,"to_many_relationships":null}],"templates":[{"name":"templates/00_struct.go.tpl","loader":"asset:templates/00_struct.go.tpl"},{"name":"templates/01_types.go.tpl","loader":"asset:templates/01_types.go.tpl"},{"name":"templates/02_hooks.go.tpl","loader":"asset:templates/02_hooks.go.tpl"},{"name":"templates/03_finishers.go.tpl","loader":"asset:templates/03_finishers.go.tpl"},{"name":"templates/04_relationship_to_one.go.tpl","loader":"asset:templates/04_relationship_to_one.go.tpl"},{"name":"templates/05_relationship_one_to_one.go.tpl","loader":"asset:templates/05_relationship_one_to_one.go.tpl"},{"name":"templates/06_relationship_to_many.go.tpl","loader":"asset:templates/06_relationship_to_many.go.tpl"},{"name":"templates/07_relationship_to_one_eager.go.tpl","loader":"asset:templates/07_relationship_to_one_eager.go.tpl"},{"name":"templates/08_relationship_one_to_one_eager.go.tpl","loader":"asset:templates/08_relationship_one_to_one_eager.go.tpl"},{"name":"templates/09_relationship_to_many_eager.go.tpl","loader":"asset:templates/09_relationship_to_many_eager.go.tpl"},{"name":"templates/10_relationship_to_one_setops.go.tpl","loader":"asset:templates/10_relationship_to_one_setops.go.tpl"},{"name":"templates/11_relationship_one_to_one_setops.go.tpl","loader":"asset:templates/11_relationship_one_to_one_setops.go.tpl"},{"name":"templates/12_relationship_to_many_setops.go.tpl","loader":"asset:templates/12_relationship_to_many_setops.go.tpl"},{"name":"templates/13_all.go.tpl","loader":"asset:templates/13_all.go.tpl"},{"name":"templates/14_find.go.tpl","loader":"asset:templates/14_find.go.tpl"},{"name":"templates/15_insert.go.tpl","loader":"asset:templates/15_insert.go.tpl"},{"name":"templates/16_update.go.tpl","loader":"asset:templates/16_update.go.tpl"},{"name":"templates/17_upsert.go.tpl","loader":"base64:(sha256 of content): b38fae3b296d86d33f75ccd1996a4ea88eb0e64327ce0f3260cc609b99e4c770"},{"name":"templates/18_delete.go.tpl","loader":"asset:templates/18_delete.go.tpl"},{"name":"templates/19_reload.go.tpl","loader":"asset:templates/19_reload.go.tpl"},{"name":"templates/20_exists.go.tpl","loader":"asset:templates/20_exists.go.tpl"},{"name":"templates/21_auto_timestamps.go.tpl","loader":"asset:templates/21_auto_timestamps.go.tpl"},{"name":"templates/singleton/boil_queries.go.tpl","loader":"asset:templates/singleton/boil_queries.go.tpl"},{"name":"templates/singleton/boil_table_names.go.tpl","loader":"asset:templates/singleton/boil_table_names.go.tpl"},{"name":"templates/singleton/boil_types.go.tpl","loader":"asset:templates/singleton/boil_types.go.tpl"},{"name":"templates/singleton/psql_upsert.go.tpl","loader":"base64:(sha256 of content): cb25b2a17877de034695accfb0a1f5f11437114d5f919062c792efee53cbb25f"},{"name":"templates_test/00_types.go.tpl","loader":"asset:templates_test/00_types.go.tpl"},{"name":"templates_test/all.go.tpl","loader":"asset:templates_test/all.go.tpl"},{"name":"templates_test/delete.go.tpl","loader":"asset:templates_test/delete.go.tpl"},{"name":"templates_test/exists.go.tpl","loader":"asset:templates_test/exists.go.tpl"},{"name":"templates_test/find.go.tpl","loader":"asset:templates_test/find.go.tpl"},{"name":"templates_test/finishers.go.tpl","loader":"asset:templates_test/finishers.go.tpl"},{"name":"templates_test/hooks.go.tpl","loader":"asset:templates_test/hooks.go.tpl"},{"name":"templates_test/insert.go.tpl","loader":"asset:templates_test/insert.go.tpl"},{"name":"templates_test/relationship_one_to_one.go.tpl","loader":"asset:templates_test/relationship_one_to_one.go.tpl"},{"name":"templates_test/relationship_one_to_one_setops.go.tpl","loader":"asset:templates_test/relationship_one_to_one_setops.go.tpl"},{"name":"templates_test/relationship_to_many.go.tpl","loader":"asset:templates_test/relationship_to_many.go.tpl"},{"name":"templates_test/relationship_to_many_setops.go.tpl","loader":"asset:templates_test/relationship_to_many_setops.go.tpl"},{"name":"templates_test/relationship_to_one.go.tpl","loader":"asset:templates_test/relationship_to_one.go.tpl"},{"name":"templates_test/relationship_to_one_setops.go.tpl","loader":"asset:templates_test/relationship_to_one_setops.go.tpl"},{"name":"templates_test/reload.go.tpl","loader":"asset:templates_test/reload.go.tpl"},{"name":"templates_test/select.go.tpl","loader":"asset:templates_test/select.go.tpl"},{"name":"templates_test/singleton/boil_main_test.go.tpl","loader":"asset:templates_test/singleton/boil_main_test.go.tpl"},{"name":"templates_test/singleton/boil_queries_test.go.tpl","loader":"asset:templates_test/singleton/boil_queries_test.go.tpl"},{"name":"templates_test/singleton/boil_suites_test.go.tpl","loader":"asset:templates_test/singleton/boil_suites_test.go.tpl"},{"name":"templates_test/singleton/psql_main_test.go.tpl","loader":"base64:(sha256 of content): 6dc1992498cb396d51c01d6cd844fe54cc03288dc886cd6bf6f333917f4c2b94"},{"name":"templates_test/singleton/psql_suites_test.go.tpl","loader":"base64:(sha256 of content): 10c471afd916418b4bfce8bafdfa4d2c01d100e1b078ee7fd065f3a143ba3ce7"},{"name":"templates_test/types.go.tpl","loader":"asset:templates_test/types.go.tpl"},{"name":"templates_test/update.go.tpl","loader":"asset:templates_test/update.go.tpl"},{"name":"templates_test/upsert.go.tpl","loader":"base64:(sha256 of content): 519b35b1d2c50c1b0e341ff900b9ad23a8b48c497b295ff189838cd490bd1701"}]}
```

**Comment by aarondl** [comment]
You definitely want to use the based on type stuff. Are you using yaml as a configuration file format? There are actually some bugs related to that.

Can you briefly try with a toml configuration that looks like:

```toml
[[imports.based_on_type]]
  name = "orb.Point"
  third_party = ['"github.com/paulmach/orb"']
```

**Comment by iamtakingiteasy** [comment]
Yes, this seems to work, while similar YAML structure is resulting in sqlboiler panicing:

    imports:
      based_on_type:
        - name: "orb.Point"
          third_party:
            - '"github.com/paulmach/orb"'

But what the point? TOML is awful and totally unreadable.

**Comment by aarondl** [comment]
Your subjective assertions hold no weight here. The bug has been identified. Working as intended and will not fix. Would accept a PR though.

**Comment by nejtr0n** [comment]
For those who looking for solution of this problem:
```
[[types]]
  # The match is a drivers.Column struct, and matches on almost all fields.
  # Notable exception for the unique bool. Matches are done
  # with "logical and" meaning it must match all specified matchers. Boolean values
  # are only checked if all the string specifiers match first, and they
  # must always match.
  # Not shown here: db_type is the database type and a very useful matcher
  [types.match]
    db_type = "USER-DEFINED"
    UDTName = "geography"

  # The replace is what we replace the strings with. You cannot modify any
  # boolean values in here. But we could change the Go type (the most useful thing)
  # or the DBType or FullDBType etc. if for some reason we needed to.
  [types.replace]
    type = "orb.Point"

  # These imports specified here overwrite the definition of the type's "based_on_type"
  # list. The type entry that is replaced is the replaced type's "type" field.
  # In the above example it would add an entry for mynull.String, if we did not
  # change the type in our replacement, it would overwrite the null.String entry.

[[imports.based_on_type]]
  name = "orb.Point"
  third_party = ['"github.com/paulmach/orb"']
```
this config will replace all geo points from database with orb.Point golanf data type
