### ISSUE TITLE
Problems with upper/lowercase char mix in primary/foreign key definitions

### ISSUE THREAD

**Issue by hoppfrosch** [volatiletech/sqlboiler#821]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.2.0

### What is your database and version (eg. Postgresql 10)
MySql - 8.x (?)

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
`sqlboiler.exe -c .\sqlboiler.toml mysql`

Using following configuration:
```
output   = "mydb_model"
wipe     = true
no-tests = true

[mysql]
  dbname  = "myDB"
  host    = "my.server.com"
  port    = 3306
  user    = "user"
  pass    = "pw"
  sslmode = "false"
  blacklist = [ .... everything execpt the two tables below ...]
```

### What is the output of the command above (without the `-d` flag)?
```
panic: could not find column name: komponente_pk [recovered]
        panic: interface conversion: string is not error: missing method Error

goroutine 1 [running]:
github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-mysql/driver.(*MySQLDriver).Assemble.func1(0xc00010fd58, 0xc00010fd50)
        C:/Go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.2.0/drivers/sqlboiler-mysql/driver/mysql.go:59 +0x78
panic(0x72b620, 0xc00018dde0)
        C:/Usr/Programme/Go/src/runtime/panic.go:969 +0x174
github.com/volatiletech/sqlboiler/v4/drivers.Table.GetColumn(0xc00000b2b0, 0xa, 0x0, 0x0, 0xc00017d400, 0x8, 0x8, 0xc000168cf0, 0x0, 0x0, ...)
        C:/Go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.2.0/drivers/table.go:41 +0x1f7
github.com/volatiletech/sqlboiler/v4/drivers.setForeignKeyConstraints(0xc000118f30, 0xc000118d80, 0x7, 0x8)
        C:/Go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.2.0/drivers/interface.go:174 +0x1ed
github.com/volatiletech/sqlboiler/v4/drivers.Tables(0x811220, 0xc000004aa0, 0xc00000b160, 0xe, 0x0, 0x0, 0x0, 0xc00017c400, 0x25, 0x40, ...)
        C:/Go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.2.0/drivers/interface.go:124 +0x179
github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-mysql/driver.(*MySQLDriver).Assemble(0xc000004aa0, 0xc000168810, 0x0, 0x0, 0x0)
        C:/Go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.2.0/drivers/sqlboiler-mysql/driver/mysql.go:104 +0x5ee
github.com/volatiletech/sqlboiler/v4/drivers.DriverMain(0x80fce0, 0xc000004aa0)
        C:/Go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.2.0/drivers/driver_main.go:37 +0x3be
main.main()
        C:/Go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.2.0/drivers/sqlboiler-mysql/main.go:9 +0x44
Error: unable to initialize tables: unable to fetch table data: driver (C:\Go\src\my.domain.com\XXX\YYY\test\bdbsqlboiler01\sqlboiler-mysql.exe) exited non-zero: exit status 2
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
Table 1:
```
CREATE TABLE `komponente` (
  `Komponente_PK` int(11) unsigned NOT NULL,
  `Komponente_Name` char(255) DEFAULT NULL,
  `Komponente_Specification` char(255) DEFAULT NULL,
  `Komponente_Major` int(11) DEFAULT NULL,
  `Komponente_Minor` int(11) DEFAULT NULL,
  `Komponente_Fixlevel` char(255) DEFAULT NULL,
  `FK_Buildjob` int(11) NOT NULL DEFAULT '-1',
  `FK_Compilertyp` int(11) DEFAULT NULL,
  PRIMARY KEY (`Komponente_PK`),
  KEY `fk_komponente_buildjob1` (`FK_Buildjob`),
  KEY `FK_Compilertyp` (`FK_Compilertyp`),
  KEY `Komponente_Name` (`Komponente_Name`),
  KEY `Komponente_Fixlevel` (`Komponente_Fixlevel`),
  KEY `Komponente_Specification` (`Komponente_Specification`),
  KEY `Komponente_Major` (`Komponente_Major`),
  KEY `Komponente_Minor` (`Komponente_Minor`),
  CONSTRAINT `FK_Compilertyp` FOREIGN KEY (`FK_Compilertyp`) REFERENCES `compilertyp` (`compilertyp_pk`),
  CONSTRAINT `fk_komponente_buildjob1` FOREIGN KEY (`FK_Buildjob`) REFERENCES `buildjob` (`buildjob_pk`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```
Table 2:
```
CREATE TABLE `komponente_zu_komponente` (
  `FK_Komponente` int(11) unsigned NOT NULL,
  `FK_Komponente_benoetigt` int(11) unsigned NOT NULL,
  `Komponente_zu_Komponente_Typ` char(255) DEFAULT NULL,
  `Komponente_zu_Komponente_Configuration` varchar(45) DEFAULT 'Default',
  PRIMARY KEY (`FK_Komponente`,`FK_Komponente_benoetigt`),
  KEY `fk_komponente_zu_komponente_komponente1` (`FK_Komponente`),
  KEY `fk_komponente_zu_komponente_komponente2` (`FK_Komponente_benoetigt`),
  CONSTRAINT `fk_komponente_zu_komponente_komponente1` FOREIGN KEY (`FK_Komponente`) REFERENCES `komponente` (`komponente_pk`),
  CONSTRAINT `fk_komponente_zu_komponente_komponente2` FOREIGN KEY (`FK_Komponente_benoetigt`) REFERENCES `komponente` (`komponente_pk`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

### Further information. What did you do, what did you expect?

We've got an existing production database (MySQL), containing 40+ tables with quite complex relations between the tables (foreign keys).
Using sqlboiler on this database, sqlboiler fails due error. 

I was able to isolate the situation causing the error - it seems to be caused by mixed usage of upper-/lowercase chars in the primary/foreign key definition (first table - primary key: * `Komponente_PK` - second table, definition of foreign key: `komponente_pk`).

As this is our long-term production database, the upper/lowercase spelling seems not to cause a problem elsewhere, and I am not able to homogenize the upper/lowercase variants.

Is there any way to use sqlboiler on this setup? Is it possible to disable case-sensitivity?

**Comment by aarondl** [comment]
There is no current way. I'm uncertain if maybe there's some way it could be accommodated properly or easily.

I think if you really wanted it to work all you would need to do is fork the mysql driver and hack it such that the FK names always came back as lowercase despite how they're defined and it might work.

A quick google around for case insensitivity in database engines reveals a nightmare, so I'm not sure I'd like to try and support it either.
