### ISSUE TITLE
Global variants are not working with CockroachDB?

### ISSUE THREAD

**Issue by BlitzpickAdmin** [volatiletech/sqlboiler#899]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.4.0

### What is your database and version (eg. Postgresql 10)
Cockroach 20.4.2

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
```go
        db, err := sql.Open("postgres", "postgres://root@localhost:26257/foo?sslmode=disable")
	if err != nil {
		return err
	}
	boil.SetDB(db)

	// log.Print(models.Foos().CountGP(ctx))
	// fails with
	//  	panic: runtime error: invalid memory address or nil pointer dereference

	// works fine
	log.Print(models.Foos().CountP(ctx, db))
```

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc7d1ff]

goroutine 1 [running]:
github.com/volatiletech/sqlboiler/v4/queries.(*Query).QueryRowContext(0xc000702300, 0x1012780, 0xc000028130, 0x0, 0x0, 0x0)
	/home/delaney/.gvm/pkgsets/go1.15.6/global/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.4.0/queries/query.go:161 +0x31f
github.com/foobar/test/sql/models.fooQuery.Count(0xc000702300, 0x1012780, 0xc000028130, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/delaney/Desktop/test/backend/sql/models/foo.go:473 +0xdf
github.com/foobar/test/sql/models.fooQuery.CountGP(0xc000702300, 0x1012780, 0xc000028130, 0x0)
	/home/delaney/Desktop/test/backend/sql/models/foo.go:448 +0xab
main.setup(0x1012780, 0xc000028130, 0x0, 0x0)
	/home/delaney/Desktop/test/backend/cmd/macrolith/main.go:55 +0x2ed
main.main()
	/home/delaney/Desktop/test/backend/cmd/macrolith/main.go:39 +0x55
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```sql
CREATE TABLE IF NOT EXISTS foo(
    id UUID PRIMARY KEY,
    bar TEXT UNIQUE,
    created_at TIMESTAMP NOT NULL
);
```

### Further information. What did you do, what did you expect?

Sure I'm using it wrong, not not sure how.

**Comment by BlitzpickAdmin** [comment]
false alarm. wasn't using "github.com/volatiletech/sqlboiler/**v4**/boil", sorry.  It is interesting that the other way worked though.
