### ISSUE TITLE
Error: unable to initialize tables: unable to fetch table data

### ISSUE THREAD

**Issue by lohmanndouglas** [volatiletech/sqlboiler#940]
I am getting the following error trying to generate the models with SQL Server, Golang 1.16.

> Error: unable to initialize tables: unable to fetch table data: driver (/home/lohmann/go/bin/sqlboiler-mssql) exited non-zero: exit status 2

I had the same database working but then I updated my computer OS and re-installed boil, but I could make it work. 

I appreciate any help to debug this issue or any relevant information. 

Instalation: 
```sh
go install github.com/volatiletech/sqlboiler/v4@latest
go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-mssql@latest
```

I am using Ubuntu 20.10
My bashrc file:
```sh
# export golang 
export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
```

### Description

SQLBoiler v4.5.0

Azure SQL server

Command to generate model
```sh
  sqlboiler mssql -c configs/boil/*.toml --wipe -d
```

```sh
using driver: /home/lohmann/go/bin/sqlboiler-mssql
panic: Not implemented [recovered]
        panic: interface conversion: string is not error: missing method Error

goroutine 1 [running]:
github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-mssql/driver.(*MSSQLDriver).Assemble.func1(0xc0003e9d68, 0xc0003e9d60)
        /home/lohmann/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.5.0/drivers/sqlboiler-mssql/driver/mssql.go:59 +0x71
panic(0x6b5fa0, 0x76bc60)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/denisenkom/go-mssqldb.passthroughConn.SetWriteDeadline(...)
        /home/lohmann/go/pkg/mod/github.com/denisenkom/go-mssqldb@v0.0.0-20200206145737-bbfc9a55622e/net.go:167
crypto/tls.(*Conn).SetWriteDeadline(...)
        /usr/local/go/src/crypto/tls/conn.go:150
crypto/tls.(*Conn).closeNotify(0xc0003b6000, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1360 +0xfd
crypto/tls.(*Conn).Close(0xc0003b6000, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1330 +0xd7
github.com/denisenkom/go-mssqldb.(*Conn).Close(0xc0001c8000, 0x0, 0x0)
        /home/lohmann/go/pkg/mod/github.com/denisenkom/go-mssqldb@v0.0.0-20200206145737-bbfc9a55622e/mssql.go:361 +0x3a
database/sql.(*driverConn).finalClose.func2()
        /usr/local/go/src/database/sql/sql.go:592 +0x49
database/sql.withLock(0x7719f0, 0xc00053a000, 0xc0003e9a50)
        /usr/local/go/src/database/sql/sql.go:3294 +0x69
database/sql.(*driverConn).finalClose(0xc00053a000, 0xc00053a020, 0x719c58)
        /usr/local/go/src/database/sql/sql.go:590 +0x13c
database/sql.(*DB).Close(0xc00011fee0, 0x5, 0x0)
        /usr/local/go/src/database/sql/sql.go:847 +0x288
github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-mssql/driver.(*MSSQLDriver).Assemble.func2(0xc00012a1e0, 0xc0003e9d60, 0xc0003e9d68)
        /home/lohmann/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.5.0/drivers/sqlboiler-mssql/driver/mssql.go:81 +0x33
github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-mssql/driver.(*MSSQLDriver).Assemble(0xc00012a1e0, 0xc0001a6900, 0x0, 0x0, 0x0)
        /home/lohmann/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.5.0/drivers/sqlboiler-mssql/driver/mssql.go:108 +0x748
github.com/volatiletech/sqlboiler/v4/drivers.DriverMain(0x772d08, 0xc00012a1e0)
        /home/lohmann/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.5.0/drivers/driver_main.go:37 +0x3eb
main.main()
        /home/lohmann/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.5.0/drivers/sqlboiler-mssql/main.go:9 +0x3d
{**OMITED JSON**{"lq":0,"rq":0,"use_index_placeholders":false,"use_last_insert_id":false,"use_schema":false,"use_default_keyword":false,"use_auto_columns":false,"use_top_clause":false,"use_output_clause":false,"use_case_when_exists_clause":false},"tables":null,"templates":null}
Error: exit status 2
driver (/home/lohmann/go/bin/sqlboiler-mssql) exited non-zero
github.com/volatiletech/sqlboiler/v4/drivers.execute
        /home/lohmann/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.5.0/drivers/binary_driver.go:73
github.com/volatiletech/sqlboiler/v4/drivers.binaryDriver.Assemble
        /home/lohmann/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.5.0/drivers/binary_driver.go:21
github.com/volatiletech/sqlboiler/v4/boilingcore.(*State).initDBInfo
        /home/lohmann/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.5.0/boilingcore/boilingcore.go:382
github.com/volatiletech/sqlboiler/v4/boilingcore.New
        /home/lohmann/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.5.0/boilingcore/boilingcore.go:93
main.preRun
        /home/lohmann/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.5.0/main.go:215
github.com/spf13/cobra.(*Command).execute
        /home/lohmann/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:841
github.com/spf13/cobra.(*Command).ExecuteC
        /home/lohmann/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        /home/lohmann/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        /home/lohmann/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.5.0/main.go:122
runtime.main
        /usr/local/go/src/runtime/proc.go:225
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1371
unable to fetch table data
github.com/volatiletech/sqlboiler/v4/boilingcore.(*State).initDBInfo
        /home/lohmann/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.5.0/boilingcore/boilingcore.go:384
github.com/volatiletech/sqlboiler/v4/boilingcore.New
        /home/lohmann/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.5.0/boilingcore/boilingcore.go:93
main.preRun
        /home/lohmann/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.5.0/main.go:215
github.com/spf13/cobra.(*Command).execute
        /home/lohmann/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:841
github.com/spf13/cobra.(*Command).ExecuteC
        /home/lohmann/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        /home/lohmann/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        /home/lohmann/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.5.0/main.go:122
runtime.main
        /usr/local/go/src/runtime/proc.go:225
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1371
unable to initialize tables
github.com/volatiletech/sqlboiler/v4/boilingcore.New
        /home/lohmann/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.5.0/boilingcore/boilingcore.go:95
main.preRun
        /home/lohmann/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.5.0/main.go:215
github.com/spf13/cobra.(*Command).execute
        /home/lohmann/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:841
github.com/spf13/cobra.(*Command).ExecuteC
        /home/lohmann/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        /home/lohmann/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        /home/lohmann/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.5.0/main.go:122
runtime.main
        /usr/local/go/src/runtime/proc.go:225
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1371
```

**Comment by aarondl** [comment]
This isn't a nice way to report errors, but the line that's breaking is here. Sorry about the ugly error.
https://github.com/volatiletech/sqlboiler/blob/master/drivers/sqlboiler-mssql/driver/mssql.go#L59

And the most likely case is that your configuration is incorrect in some way. Since you haven't provided it I can't help any more than tell you to check out the docs again.

**Comment by stefkampen** [comment]
I have created this pull request to fix the error: https://github.com/volatiletech/sqlboiler/pull/947
